version: '2.0.0-develop-{build}'
image: Visual Studio 2019
before_build:
  - nuget restore Parse.sln
build_script:
  project: Parse.sln
  verbosity: minimal
before_test:  
  - choco install opencover.portable
  - choco install codecov
test_script:
  - OpenCover.Console.exe -target:dotnet.exe -targetargs:"test --test-adapter-path:. --logger:Appveyor /p:DebugType=full .\Parse.Tests\Parse.Tests.csproj" -filter:"+[Parse*]* -[Parse.Tests*]*" -oldstyle -output:parse_sdk_dotnet_coverage.xml -register:user
after_test:
  - codecov -f "parse_sdk_dotnet_coverage.xml"
artifacts:
  - path: '**\*.nupkg'
    name: Parse NuGet Package